#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Nov 16, 2025 08:17:44 PM CST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import myCTP_support
#from myCTP_support import fontName, fontSize, fontSize_int

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0


def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: myCTP_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'default.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('default')
    style.configure('.', font = "TkDefaultFont")
    if sys.platform == "win32":
       style.theme_use('winnative')    
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("665x639+1194+239")
        top.minsize(1, 1)
        top.maxsize(4145, 1570)
        top.resizable(1,  1)
        top.title("CTP500 Printer App")

        self.top = top
        self.fontSize = tk.StringVar()
        self.fontSize.set('18')
        self.radioJustification_status = tk.IntVar()

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        ########### start #######################
        ########### end #######################

        self.Labelframe1 = tk.LabelFrame(self.top)
        self.Labelframe1.place(x=13, y=20, height=259, width=636)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(borderwidth="5")
        self.Labelframe1.configure(text='''Text''')

        self.Label1 = tk.Label(self.Labelframe1)
        self.Label1.place(x=537, y=131, height=28, width=77, bordermode='ignore')

        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(anchor='w')
        self.Label1.configure(compound='left')
        self.Label1.configure(text='''Font Size''')

        self.Button1 = tk.Button(self.Labelframe1)
        self.Button1.place(x=20, y=197, height=37, width=161
                , bordermode='ignore')
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(compound='left')
        self.Button1.configure(text='''Load a text file''')
        self.Button1.configure(command=lambda: myCTP_support.selectTextFile(self))        
        self.Text1_1 = tk.Text(self.Labelframe1)
        self.Text1_1.place(x=10, y=22, height=168, width=497
                , bordermode='ignore')
        self.Text1_1.configure(background="white")
        self.Text1_1.configure(exportselection="0")
        self.Text1_1.configure(font="TkTextFont")
        self.Text1_1.configure(padx="0")
        self.Text1_1.configure(pady="0")
        self.Text1_1.configure(selectbackground="#d9d9d9")
        self.Text1_1.configure(undo="1")
        self.Text1_1.configure(wrap="word")
        self.Text1_1.configure(font=(myCTP_support.fontName, myCTP_support.fontSize_int))

        self.Button2 = tk.Button(self.Labelframe1)
        self.Button2.place(x=400, y=197, height=37, width=101
                , bordermode='ignore')
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(compound='left')
        self.Button2.configure(text='''Print Text''')
        self.Button2.configure(command=lambda: myCTP_support.print_from_entry(self))        

        _style_code()
        self.TLabelframe1_1 = ttk.Labelframe(self.Labelframe1)
        self.TLabelframe1_1.place(x=515, y=23, height=108, width=110
                , bordermode='ignore')
        self.TLabelframe1_1.configure(relief='')
        self.TLabelframe1_1.configure(text='''Justification''')

        self.Radiobutton1_1 = tk.Radiobutton(self.TLabelframe1_1)
        self.Radiobutton1_1.place(x=9, y=26, height=22, width=97
                , bordermode='ignore')
        self.Radiobutton1_1.configure(activebackground="#d9d9d9")
        self.Radiobutton1_1.configure(anchor='w')
        self.Radiobutton1_1.configure(compound='left')
        self.Radiobutton1_1.configure(justify='left')
        self.Radiobutton1_1.configure(text='''Left''')
        self.Radiobutton1_1.configure(value='0')
        self.Radiobutton1_1.configure(variable=self.radioJustification_status)
        self.Radiobutton1_1.config(state=tk.DISABLED) # Not yet implemented

        self.Radiobutton2_1 = tk.Radiobutton(self.TLabelframe1_1)
        self.Radiobutton2_1.place(x=9, y=52, height=21, width=94
                , bordermode='ignore')
        self.Radiobutton2_1.configure(activebackground="#d9d9d9")
        self.Radiobutton2_1.configure(anchor='w')
        self.Radiobutton2_1.configure(compound='left')
        self.Radiobutton2_1.configure(justify='left')
        self.Radiobutton2_1.configure(text='''Center''')
        self.Radiobutton2_1.configure(value='1')
        self.Radiobutton2_1.configure(variable=self.radioJustification_status)
        self.Radiobutton2_1.config(state=tk.DISABLED) # Not yet implemented

        self.Radiobutton3_1 = tk.Radiobutton(self.TLabelframe1_1)
        self.Radiobutton3_1.place(x=9, y=78, height=21, width=79
                , bordermode='ignore')
        self.Radiobutton3_1.configure(activebackground="#d9d9d9")
        self.Radiobutton3_1.configure(anchor='w')
        self.Radiobutton3_1.configure(compound='left')
        self.Radiobutton3_1.configure(justify='left')
        self.Radiobutton3_1.configure(text='''Right''')
        self.Radiobutton3_1.configure(value='2')
        self.Radiobutton3_1.configure(variable=self.radioJustification_status)
        self.Radiobutton3_1.config(state=tk.DISABLED) # Not yet implemented

        self.TCombobox1_1 = ttk.Combobox(self.Labelframe1)
        self.TCombobox1_1.place(x=540, y=160, height=38, width=69
                , bordermode='ignore')
        self.value_list = ['6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43','44','45','46','47','48','49','50','51','52','53','54','55']
        self.TCombobox1_1.configure(values=self.value_list)
        self.TCombobox1_1.configure(exportselection="0")
        self.TCombobox1_1.configure(textvariable=self.fontSize)
        self.TCombobox1_1.bind(
            '<<ComboboxSelected>>', 
            lambda event: myCTP_support.changeFont(self))
    
        self.Labelframe2 = tk.LabelFrame(self.top)
        self.Labelframe2.place(x=13, y=300, height=315, width=636)
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(borderwidth="5")
        self.Labelframe2.configure(text='''Image''')

        self.imageCanvas = tk.Canvas(self.Labelframe2)
        self.imageCanvas.place(x=10, y=30, height=270, width=384
                , bordermode='ignore')
        self.imageCanvas.configure(background="#ffffff")
        self.imageCanvas.configure(borderwidth="2")
        self.imageCanvas.configure(relief="ridge")
        self.imageCanvas.configure(selectbackground="#d9d9d9")

        self.Button4 = tk.Button(self.Labelframe2)
        self.Button4.place(x=450, y=160, height=37, width=128
                , bordermode='ignore')
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(compound='left')
        self.Button4.configure(text='''Print Image''')
        self.Button4.configure(command=lambda: myCTP_support.print_from_image(self))

        self.Button3 = tk.Button(self.Labelframe2)
        self.Button3.place(x=450, y=100, height=37, width=128
                , bordermode='ignore')
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(compound='left')
        self.Button3.configure(cursor="fleur")
        self.Button3.configure(text='''Select Image''')
        self.Button3.configure(command=lambda: myCTP_support.selectImageFile(self))

#def start_up():
#    myCTP_support.main()

if __name__ == '__main__':
    myCTP_support.main()

#start_up()



